(setq X '(1))
(message "1")
(require 'package)
(setq X (cons 2 X))
(message "2")
;; optional. makes unpure packages archives unavailable
(setq package-archives nil)
(setq X (cons 3 X))
(message "3")
(setq package-enable-at-startup nil)
(setq X (cons 4 X))
(message "4")
(setq load-path
      (seq-filter #'(lambda (x) (not (string-prefix-p "/home/hcarr/.emacs.d" x)))
		  load-path))
(setq X (cons 5 X))
(message "5")
(package-initialize)
(setq X (cons 6 X))
(message "6")
