#+OPTIONS: num:nil
#+Title: Haskell / Emacs Dev Env

This is my emacs/haskell development environment.

I switch from Intero to Dante because Dante works with cabal, [[https://nixos.org/nix/][nix]], etc., whereas Intero only works with [[https://docs.haskellstack.org/en/stable/README/][Stack]].

Note: much of this works with [[https://commercialhaskell.github.io/intero/][intero]].  See: [[https://github.com/cydparser/demo-emacs-haskell/]]

# Created       : 2017 Oct 24 (Tue) 17:20:43 by Harold Carr.
Last Modified : 2017 Oct 24 (Tue) 18:12:23 by Harold Carr.

------------------------------------------------------------------------------
* setup

Get =.haskell-minimal-init.el= from [[https://github.com/haroldcarr/emacs]].

Also get the files it references from the same repo.

#+begin_example
emacs -q -l <path to>/.haskell-minimal-init.el
#+end_example

------------------------------------------------------------------------------
* [[https://github.com/bbatsov/projectile][projectile]]

project navigation, building, testing, ...

Keybindings (subset)
- =C-c p != : projectile-run-shell-command-in-root
- =C-c p c= : projectile-compile-project
- =C-c p f= : projectile-find-file
- =C-c p k= : projectile-kill-buffers
- =C-c p t= : projectile-toggle-between-implementation-and-test

To see full list, if [[https://github.com/justbur/emacs-which-key][whick-key]] is install: press =C-c p= and wait.

try:
- go to any directory in a project
- =C-c p f=
- type a filename from anywhere in the project
- use =C-p= and =C-n= to navigate list of candidates
- press =RET= to go to that file

------------------------------------------------------------------------------
* [[http://github.com/joaotavora/yasnippet][yasnippet]] / [[https://github.com/haskell/haskell-snippets][haskell-snippets]]

some templates (to see full list: =M-x yas/describe-tables=)
| =mod=  | adds a named (based on filepath) module declaration |
| =main= | adds a =Main= module and =main= function            |
| =lang= | adds a =LANGUAGE= pragma                            |
| =opt=  | adds a =OPTIONS_GHC= pragma                         |

try:
- open new file =List.hs=
- type =mod=
- press =M-/= (hippie-expand)
- select =simple module=
- press =RET=
- press =tab= to accept default module name (or start typing)

------------------------------------------------------------------------------
* haskell

--------------------------------------------------
** haskell-hoogle (part of [[https://github.com/haskell/haskell-mode][haskell-mode]])

*** search by name

try:
- in a haskell file, point to something provided by external library or GHC
- =M-x hayoo= (using [[http://hayoo.fh-wedel.de/][Hayoo!]])
- =M-x hoogle= (using [[https://www.haskell.org/hoogle/][Hoogle]])

*** search by type

try:
- =M-x hayoo= or =hoogle=
- enter : =f a -> Maybe c= RET

--------------------------------------------------
** [[https://github.com/jyp/dante][dante]]

--------------------------------------------------
*** view types / info

try:

*types*

- point to something
- =C-c .= : dante-type-at

*info* (shows definition and where defined, even if external)

- point to something
- =C-c ,= : dante-info

--------------------------------------------------
*** definitions and references

**** definitions

- point to something
- =M-.= : jump to definition
- =M-,= : return to previous location

**** references

- point to something
- =M-?= : xref-find-references (TODO : DOES NOT WORK FOR ME)

--------------------------------------------------
*** apply suggestions / auto-fix

try:

- add the following code to =List.hs=

#+begin_example
data List a = Cons a (List a) | Nil
  deriving (Eq, Foldable, Show)
#+end_example

- see red squiggly line under =Foldable=
- =C-c ! l= : flycheck-list-errors
- says "... You need DeriveFoldable ..."
- =C-c /=   : dante-auto-fix
- (inserts appropriate =LANGUAGE= pragma)

--------------------------------------------------
*** add type info

try:

- add to =List.hs=

#+begin_example
cdr Nil = Nil
cdr (Cons _ xs) = xs
#+end_example

- see red squiggly line under =cdr=
- =C-c ! l= : flycheck-list-errors
- says "... Top-level binding with no type signature ..."
- =C-c /= : dante-auto-fix
- (inserts appropriate type signature)

--------------------------------------------------
*** doctest

try:

- add to =List.hs=

#+begin_example
-- | Returns the first element, if non-empty.
--
-- >>> car Nil
--
-- >>> car (Cons 'a' Nil)
car :: List a -> Maybe a
car xs = case xs of
  Nil      -> Nothing
  Cons x _ -> Just x
#+end_example

- point inside comment
- =C-c "= : dante-eval-block
- (inserts function call results)

# TODO : run tests after results specified

--------------------------------------------------
*** process buffer

If dante starts acting weird, restart it.

#+begin_example
M-x dante-list-buffers RET
d ;; mark process for deletion
x ;; kill it
q ;; quit process list
M-x dante-restart RET
#+end_example

--------------------------------------------------
* completion via [[https://company-mode.github.io/][company]]

Dante source has =dante-company= function that integrates it with =company=.

try:

- in =List.hs=
- type : =import System.E=
- =M-n= or =M-p= : move through suggestions
- note: delete =E= until only : =import System.=
- now shows all packages in =System=

--------------------------------------------------
* projectile / test files

try:

- from =List.hs=
- =C-c p t=
- finds and jumps to (or creates) =ListSpec.hs=

--------------------------------------------------
* projectile / build and run

- =C-c p c= : build
- =C-c p != : run

--------------------------------------------------
* formatting

- =M-x haskell-mode-stylish-buffer=

